#!/bin/bash

NIMBUL_HOME=$(dirname $0)

echo "Starting Nimbul and daemons, please wait..."

# source /etc/cloudrc if it exists
if [ -f /etc/cloudrc ]; then
    source /etc/cloudrc
fi

cd "${NIMBUL_HOME}"
script/server -d
script/daemons start

echo "Done"

exit 0
